### ISSUE TITLE
Docker causing new Initialization screen with each update.

### ISSUE THREAD

**Issue by ghormann** [FalconChristmas/fpp#1974]
From FaceBook:

Has anyone had any issues with docker and FPP reverting to a blank initial setup every time new images are pulled? When I do a compose down, compose pull, and compose up -d I am greated with the FPP initial setup screen again. It seems like if I take the stack down and simply bring it back up again, this doesn't happen. Once I go through the initial setup again, it seems to be fine. Any thoughts?

A volume for media is defined 

![image](https://github.com/user-attachments/assets/88bca715-5a5c-4354-8f4d-af38fe2b85b3)

**Comment by docwisdom** [comment]
Yes, I am having this issue, using Unraid app deployment of the docker image

**Comment by ghormann** [comment]
@docwisdom   Can you give a process to reproduce.   Here is what I did
1) Build an older version locally from a few commits back and called it "falconchristmas/fpp:old"
2) used the docker-compose below to start it up  
3) Moved though the initial setup
4) shutdown (docker-compose down
5) change the file to use falconchristmas/fpp:latest
6) run docker-compose up
The initial screen did *NOT* appear.

```yaml
services:
  fpp-docker:
    container_name: fpp-docker
    image: falconchristmas/fpp:old
    restart: always

    # FPP will report this hostname via MultiSync
    hostname: fpp-docker

    volumes:
      - ./media:/home/fpp/media
      # Uncomment the following line if you create a 'fpp' subdirectory
      # containing a git clone of the FPP code repository.  This is mainly
      # for developer use
      #- ./fpp:/opt/fpp

    environment:
      # To allow the instance to report its external IP, you can optionally
      # define a FPP_DOCKER_IP environment variable with the external IP
      #      - FPP_DOCKER_IP=192.168.1.10
      - TZ=America/Los_Angeles

    # By Default, we don't run privileged containers.  If you need to
    # access the sound card, this may be required.

    # privileged: true

    ports:
        - 80:80
```
