### ISSUE TITLE
Configuration loss on container restart

### ISSUE THREAD

**Issue by Nooton92** [FalconChristmas/fpp#2063]
**NOTE:** IF YOU DO NOT ATTACH YOUR LOG FILES, THEN THERE IS A HIGHER PROBABILITY THE ISSUE WON'T BE RESOLVED.  (Steps at end) 
# Please answer the following:
**FPP Version and Hardware**: 
8.x-master-729-ga6cdccee
Running in UnRaid on a T330 poweredge

**Describe the bug and Steps to reproduce**: 
On container restart all configuration is lost. Opening the webUI brings me to the first time set up requiring password setting, location, etc. and all controllers, playlists etc. need to be set up again.

**Expected behavior**: 
Once config is set it should not be wiped on a container restart.
[FPP_Logs_20241125.0046.zip](https://github.com/user-attachments/files/17895803/FPP_Logs_20241125.0046.zip)

**Comment by ghormann** [comment]
What persistent volumes are you mounting?   If you don't have a volumne for `/home/fpp/media` this would explain the problem.

**Comment by Nooton92** [comment]
![Screenshot_20241124-182850](https://github.com/user-attachments/assets/36cd0d63-c863-4c6c-b008-b6d8c2ad6327)
I have /home/FPP mounted so all subfolders should be covered already correct?

**Comment by ghormann** [comment]
I'm struggling to reproduce this with newer (8,.3+) builds.   I even tried starting with an 8.3 and then upgrading to latest and it remembered my configuration.     here is the docker-compose file I'm using: 
```yaml
# Setup:
#
# mkdir /docker/fpp-docker
# cd /docker/fpp-docker
# wget -O ./docker-compose.yml https://raw.githubusercontent.com/FalconChristmas/fpp/master/Docker/docker-compose.yml
# mkdir media
# chmod 770 media
# chown 500:500 media

# To start the container and keep it running:
#
# cd /docker/fpp-docker
# docker-compose up -d

# To stop the running container:
#
# cd /docker/fpp-docker
# docker-compose down

services:
  fpp-docker:
    container_name: fpp-docker
    image: falconchristmas/fpp:latest
    restart: always

    # FPP will report this hostname via MultiSync
    hostname: fpp-docker

    volumes:
      - ./media:/home/fpp/media

    environment:
      # To allow the instance to report its external IP, you can optionally
      # define a FPP_DOCKER_IP environment variable with the external IP
      #      - FPP_DOCKER_IP=192.168.1.10
      - TZ=America/Los_Angeles

    # By Default, we don't run privileged containers.  If you need to
    # access the sound card, this may be required.

    # privileged: true

    ports:
        - 80:80

```
