### ISSUE TITLE
Muti-arch docker image including ARM

### ISSUE THREAD

**Issue by akutruff** [FalconChristmas/fpp#898]
**Is your feature request related to a problem? Please describe.**

A multi-arch docker image attached to falconchristmas/fpp would be great!  I already did a docker build of the image for arm64 and have it running fine on a RPi 3.  No modifications of the source were needed.

**Describe the solution you'd like**

I built it directly a Pi4 using:

```docker build -t akutruff/fpp:latest -f Docker/Dockerfile .```

To build multi-arch in one-go on a typical Linux machine this is what I would try:  

```
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t akutruff/fpp:latest --push -f Docker/Dockerfile .
```

It should work, but I have not tested when built with the QEmu used by buildx.

Testing:

Here is the docker compose.yml I used after doing the arm64 build.  It maintains user data between restarts and allows access to headphone output.

```
version: "3.4"

services:
  fpp:
    image: akutruff/fpp
    volumes:
      - data:/opt/fpp
      - media:/home/fpp/media
    network_mode: host
    devices:
      - "/dev/snd:/dev/snd"
    restart: unless-stopped

volumes:
    data:
    media:
```

**Describe alternatives you've considered**

**Additional context**
